### ISSUE TITLE
【已证明是我误会，接口没问题】下载的文件统一为 4.85k 的损坏文件

### ISSUE THREAD

**Issue by isPoto** [huankong233/lanzou_url#1]
解析没问题，但是下载下来的文件均是 4.85k 大小的损件。
包括详情页的示例，一个 14M 的字体文件，下载下来也是 4.85k 的损件。

**Comment by huankong233** [comment]
![Screenshot_2022-11-27-07-57-01-928_com android providers downloads ui](https://user-images.githubusercontent.com/49610758/204113260-22f9e288-6f69-47f4-b42f-3404e9084531.jpg)
奇怪，我咋没问题，没事，有空应该要重写的，一坨屎山了

**Comment by huankong233** [comment]
不能用的话可以考虑用alist凑合一下

**Comment by isPoto** [comment]
破案了

下载有人机检测

而我是用下载器下载的，没有做报错处理。所以变成了下载人机检测的网页。

API 本身没有任何问题，是我这里的使用问题。

代码不用重写，体验非常满意。

感谢你开发如此好用的接口！

**Comment by huankong233** [comment]
马上重写完了（），应该速度有提升

**Comment by huankong233** [comment]
下载人机检测是什么页面
是用的我的服务嘛，被cloudflare拦截了?还是被蓝奏的拦截了

**Comment by isPoto** [comment]
你那里可以直接下载？我这里下载蓝奏云的文件，无论是官方下载还是解析直链下载，都会有如图所示的人机验证页面。

![image](https://user-images.githubusercontent.com/59009389/204135065-0cbafc12-3e17-4940-8f83-4ff18110eb99.png)

我这次反馈也是因为下载器没有适配人机验证的情况，本来是想下文件，因为多了人机验证这一步，便把人机验证的网页给错误地下了下来。

图片是以详情页下载字体文件的示例，那个直链网址访问得到的。

https://developer.lanzoug.com/file/?AGYFOwEwVGUGDwM7BDECbgM8UmoCMFcmVykBb1QmUCUCdlBhAXoAMgA/ATtUZVcJADMFZFEzVmECM1trUjcBOAA3BWoBaFQmBjYDJgRtAjIDbFJnAmtXYldnATNUPFB3AnJQdwFhAGYAZgFlVDFXeQBrBTFRIVZmAjRbclI/AWEAZAUwAWVUZQZjAzYENAI0A29SNAI5V2JXZwExVGlQZQIwUD8BbgBsAGYBZFQ0V28AawU0UTlWNQJgWztSIAF0AHQFNAF6VHUGIwMwBCICagM9UmoCZFdnV2IBP1Q4UGkCJFBzATUAOQAzATFUPVdnAGwFNlE3VmECMFtvUjsBMwA0BXQBOlRsBicDaARhAjUDb1JuAmhXZFdgAT5UP1BhAiRQcgEsACMAawFmVDZXZQBtBTRROFZhAj1baVI7ASYAdQU7ASxUPQZhA2IEYwItA2FSZQJzV2dXYgEyVCZQYAIyUDABegAwADoBalQw

**Comment by huankong233** [comment]
这个页面是一个js加密页面，我给你找一下解密的方法吧

**Comment by huankong233** [comment]
https://github.com/zaxtyson/LanZouCloud-API/blob/ab2e9ec715d1919bf432210fc16b91c6775fbb99/lanzou/api/core.py#L452

**Comment by byludy** [comment]
请求的时候带上头 'Accept-Language', 'zh-CN,zh;q=0.9'
可以下载
