### ISSUE TITLE
[Bug]文件夹解析错误

### ISSUE THREAD

**Issue by NakanoSanku** [huankong233/lanzou_url#12]
- url: https://katetseng.lanzoue.com/b00r4c8ah
- password: 9jw9
- 部署方式:vercel
```
https://lanzou-straight-chain-analysis.vercel.app/api/?url=https://katetseng.lanzoux.com/b00r4c8ah&9jw9&pass=9jw9
```
解析大佬readme中的文件夹正常，自己新创建的文件夹返回203，大佬的示例api返回一样结果
改成lanxzoux也无法正常解析
单文件解析/id均正常
![image](https://github.com/huankong233/lanzou_url/assets/96334375/9e4ae122-55ff-46ad-bd89-a25e374ce9cc)

**Comment by huankong233** [comment]
奇怪，我api示例我看可以请求

**Comment by huankong233** [comment]
但是你的不行

**Comment by huankong233** [comment]
找到问题了，pgs参数正则没匹配到

**Comment by huankong233** [comment]
fixed on commits: 
https://github.com/huankong233/lanzou_url/commit/354d5d8a9c13181257269628f20b76884147e092
https://github.com/huankong233/lanzou_url/commit/1d472879fe02f3597fd6ba27ee7d927df4c7bb50
