### ISSUE TITLE
好像不能用了

### ISSUE THREAD

**Issue by wmz1024** [huankong233/lanzou_url#7]
我检查参数都是对的 但是他显示无参数

**Comment by huankong233** [comment]
应该没问题，我在我服务器上部署的还是正常的

但是有密码的好像不能用了(部分)，会返回密码错误

**Comment by huankong233** [comment]
带有密码的页面变了，没带密码和带密码的文件夹页面都没变，把带密码的页面再改一下就可以

**Comment by huankong233** [comment]
应该[解决](https://github.com/huankong233/lanzou_url/commit/876143526252a9ee7f19892cbf59140d02066f69)了

**Comment by huankong233** [comment]
更新一下vercel吧

**Comment by wmz1024** [comment]
好的 我这就更新Vercel版本
